### ISSUE TITLE
[BUG] 下载时连接超时

### ISSUE THREAD

**Issue by xiuzenb** [CreatechStudio/MC-Mod-Integration#9]
### 问题描述

如题，无法从HMCL中拉取client.jar

### 复现方法

1. 使用CDN 1.19 安装

### 你认为造成此问题的模组

1. 

### 操作系统类型

Windows

### 操作系统版本

21H2

### JDK版本

java 17.0.3.1 2022-04-22 LTS Java(TM) SE Runtime Environment (build 17.0.3.1+2-LTS-6) Java HotSpot(TM) 64-Bit Server VM (build 17.0.3.1+2-LTS-6, mixed mode, sharing)

### 启动日志

```text
无
```

### 额外说明

DNS阿里云
电信
Windows
[![vQqqYt.jpg](https://s1.ax1x.com/2022/08/08/vQqqYt.jpg)](https://imgtu.com/i/vQqqYt)

### 协议

- [X] 我已查阅[Issue列表](https://github.com/CreatechStudio/MC-Mod-Integration/issues?q=is%3Aopen+is%3Aissue+label%3A%E9%97%AE%E9%A2%98)，并确认我的问题不在其中。
- [ ] 我确认我已认真阅读所有注意事项并认真填写表单。

**Comment by lightumcc** [comment]
检疫检查HMCL版本

**Comment by xiuzenb** [comment]
Hello Minecraft! Launcher v3.5.3

**Comment by lightumcc** [comment]
那有试过删除配置文件吗

**Comment by xiuzenb** [comment]
Hello Minecraft! Launcher v3.5.3

**Comment by xiuzenb** [comment]
试过了

**Comment by lightumcc** [comment]
那我就不是很清楚了，先挂在这里吧

**Comment by lightumcc** [comment]
可能是Mojang的服务器坏了

**Comment by lightumcc** [comment]
使用加速下载站即可解决
